server:
  port: 80
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:oracle:thin:@211.101.37.237:1521:orcl
    username: tjbhzc
    password: tjbhzc
    driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
